### ISSUE TITLE
Fix Decimal Residency Values

### ISSUE THREAD

**Issue by sherpdawerp** [drehtisch/NationStatesAPIBot#39]
When a nation has a decimal residency value, i.e. 0.12345, the code treats it as being a residency value of 12345, no decimal. 

The NS API returns these values as decimals without a problem, and I suspect the issue comes when running this: `var residencyDbl = Convert.ToDouble(residency, _locale);` operation on the residency value. 

The rest of the residency operations (calculating number of years, calculating number of days) all seem logical and working, but I can't test outputs to verify that.

**Comment by drehtisch** [comment]
I investigated this issue. It turns out that the parsed locale info was null which causes the conversion to interpret "1.234" as "1234". I have a fix ready and will push it soon.
